#!/usr/bin/env python3
"""
Scaffold the translation work packets for one test and one target language.

    python3 .agents/exam-answer-translation/scripts/scaffold_translation.py \
        tests/20260807_1 --lang vi --label "Tiếng Việt"
    make scaffold-translation 20260807_1 TLANG=vi TLABEL="Tiếng Việt"

Reads  tests/<id>/詳細解説.json  (the Japanese explanations — the single source
of truth for what a translation may say) and writes, under the gitignored
working directory tests/<id>/_translation/<lang>/:

    meta.json             language, source digest, chunk list
    chunk-NN.json         one read-only work packet per group of items
    chunk-NN.target.json  written by the translator, holding ONLY translations

The packet is never edited: the translator writes the matching `.target.json`
beside it, mirroring the packet's keys and array lengths. Splitting them keeps
the Japanese source out of the translator's output — a 40k-character rewrite
of a file it only had to read is where a truncated or mangled packet comes
from — and makes re-translating one item a small diff.

Reading passages and listening scripts are DEDUPLICATED into the packet's
`shared` block — 問題11 spends one passage over three items, and translating
it three times is both wasted work and three chances to disagree with itself.
merge_translation.py expands each shared translation back onto every item that
referenced it.

This script never names a language: --lang/--label come from the caller
(GENERATE.md declares which languages a paper ships with).
"""

import argparse
import hashlib
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
UI_DIR = ROOT / ".agents/exam-answer-translation/ui"
TRANSLATABLE = ("why_correct", "options_analysis", "points")

INSTRUCTIONS = (
    "Do not edit this file. Write the translations into the sibling file named by "
    "\"output\", shaped {\"shared\": {ref: \"…\"}, \"items\": {key: {\"why_correct\": \"…\", "
    "\"options_analysis\": [...], \"points\": [...]}}} — every ref, every item key, and "
    "arrays exactly as long as their source counterpart. \"stem\"/\"options\" are reference "
    "context only and are not translated. Keep Japanese exam terms (the tested word, the "
    "grammar pattern, quoted lines) in Japanese inside the translated sentence; translate "
    "the explanation around them. No [正解]/[不正解]-style tags — the page adds them."
)


def slug_ok(lang: str) -> bool:
    return bool(re.fullmatch(r"[a-z]{2,3}(-[a-z0-9]{2,8})?", lang))


def digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def scaffold(test_dir: Path, lang: str, label: str, chunk_size: int, force: bool) -> Path:
    test_dir = Path(test_dir).resolve()
    src_path = test_dir / "詳細解説.json"
    if not src_path.is_file():
        raise SystemExit(f"no {src_path} — run `make scaffold-explanations {test_dir.name}` first")
    if not slug_ok(lang):
        raise SystemExit(f"--lang must be a BCP-47-ish code like 'vi' or 'zh-hant', got {lang!r}")

    raw = src_path.read_text(encoding="utf-8")
    source = json.loads(raw)
    source.pop("_meta", None)

    work = test_dir / "_translation" / lang
    if work.exists():
        if not force:
            raise SystemExit(
                f"{work} already exists — finish or delete it, or pass --force to re-scaffold "
                f"(re-scaffolding DISCARDS every translation already typed into it)"
            )
        shutil.rmtree(work)
    work.mkdir(parents=True)

    # Deduplicate passages/scripts: one id per distinct Japanese text, emitted in
    # the packet where it is first referenced.
    shared_id: dict[tuple[str, str], str] = {}
    item_refs: dict[str, dict[str, str]] = {}
    for key, item in source.items():
        refs = {}
        for kind, prefix in (("passage", "p"), ("script", "s")):
            text = item.get(kind)
            if not text:
                continue
            sig = (kind, text)
            if sig not in shared_id:
                shared_id[sig] = f"{prefix}{len(shared_id) + 1}"
            refs[f"{kind}_ref"] = shared_id[sig]
        item_refs[key] = refs

    keys = list(source.keys())
    chunks = [keys[i:i + chunk_size] for i in range(0, len(keys), chunk_size)]
    emitted: set[str] = set()
    chunk_names = []

    for n, chunk_keys in enumerate(chunks, 1):
        name = f"chunk-{n:02d}.json"
        chunk_names.append(name)
        shared_block = {}
        items_block = {}
        for key in chunk_keys:
            item = source[key]
            refs = item_refs[key]
            for kind in ("passage", "script"):
                ref = refs.get(f"{kind}_ref")
                if ref and ref not in emitted:
                    emitted.add(ref)
                    shared_block[ref] = {"kind": kind, "source": item[kind]}
            entry = {
                "stem": item.get("stem", ""),
                "options": item.get("options", []),
            }
            entry.update(refs)
            entry["source"] = {
                "why_correct": item.get("why_correct", ""),
                "options_analysis": list(item.get("options_analysis") or []),
                "points": list(item.get("points") or []),
            }
            items_block[key] = entry

        payload = {
            "test_id": test_dir.name,
            "lang": lang,
            "chunk": name,
            "output": name.replace(".json", ".target.json"),
            "instructions": INSTRUCTIONS,
            "shared": shared_block,
            "items": items_block,
        }
        (work / name).write_text(
            json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    ui_path = UI_DIR / f"{lang}.json"
    if not ui_path.is_file():
        template = json.loads((UI_DIR / "_template.json").read_text(encoding="utf-8"))
        template["_comment"] = (
            f"UI labels for '{lang}'. Values are still the Japanese originals — translate "
            f"every one of them (keep the {{n}} placeholder in question_label)."
        )
        ui_path.write_text(json.dumps(template, ensure_ascii=False, indent=2) + "\n",
                           encoding="utf-8")
        print(f"  · created {ui_path.relative_to(ROOT)} — TRANSLATE ITS VALUES (still Japanese)")

    meta = {
        "test_id": test_dir.name,
        "lang": lang,
        "label": label,
        "source": "詳細解説.json",
        "source_sha256": digest(raw),
        "items": len(source),
        "shared": len(shared_id),
        "chunks": chunk_names,
    }
    (work / "meta.json").write_text(json.dumps(meta, ensure_ascii=False, indent=2) + "\n",
                                    encoding="utf-8")

    print(f"✓ scaffolded {len(chunk_names)} packet(s) for {test_dir.name} [{lang}] in "
          f"{work.relative_to(ROOT)}")
    print(f"  {len(source)} items, {len(shared_id)} deduplicated passage/script text(s)")
    print(f"  next: write every chunk-NN.target.json, then "
          f"`make merge-translation {test_dir.name} TLANG={lang}`")
    return work


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1],
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("test_dir", help="path to the test directory (e.g. tests/20260807_1)")
    ap.add_argument("--lang", required=True, help="target language code (e.g. vi)")
    ap.add_argument("--label", default="", help="native language name shown on the toggle")
    ap.add_argument("--chunk-size", type=int, default=20, help="items per work packet (default 20)")
    ap.add_argument("--force", action="store_true", help="delete and re-scaffold existing packets")
    args = ap.parse_args()
    scaffold(Path(args.test_dir), args.lang, args.label or args.lang,
             args.chunk_size, args.force)


if __name__ == "__main__":
    sys.exit(main())
